services:
  - type: web
    name: forumx-frontend
    env: static
    buildCommand: npm install && npm install -g vite && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PATH
        value: ${PATH}:${HOME}/.npm-global/bin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
